refactor: apply webpack defaults
webpack-contrib/null-loader pull request #8
Opened 2017-04-09 06:14 UTC by d3viant0ne

Intended to be merged & released as a part of `1.0.0` on a beta `dist-tag` once this has been finished and properly tested.

BREAKING CHANGE: 

Enforces NodeJS > 4.3 via engines 

Closed #7

2017-04-09 09:17 UTC, michael-ciniawsky requested changes

2017-04-09 09:17 UTC, michael-ciniawsky commented on package.json
> +  ],
```
"repository": {
    "type": "git",
    "url": "git+https://github.com/webpack-contrib/null-loader.git"
  },
  "bugs": {
    "url": "https://github.com/webpack-contrib/null-loader/issues"
  },
  "homepage": "https://webpack.js.org",
```

2017-04-09 09:17 UTC, michael-ciniawsky commented on src/index.js
> +  this.cacheable();
```diff
- this.cacheable();
```

2017-04-09 09:17 UTC, michael-ciniawsky commented on src/index.js
> +  this.cacheable();
```diff
- this.cacheable();
```

2017-05-02 08:46 UTC, michael-ciniawsky approved these changes

2017-05-02 09:03 UTC, d3viant0ne commented
So if I find a good way to test `nothing` do I win some sort of prize?

2017-05-02 09:08 UTC, michael-ciniawsky commented
The **all and nothing** award is yours 🥇 😛

2018-04-05 03:19 UTC, shellscape approved these changes

2018-04-05 03:19 UTC, merged